### ISSUE TITLE
Documentation Restructuring (2nd Review)

### ISSUE THREAD

**Issue by FantasticoFox** [ethersphere/swarm-docs#18]
2nd Review of the documentation restructuring before ensuring that https://swarm-guide.readthedocs.io is linking to it.

https://github.com/ethersphere/swarm-docs

**Comment by nolash** [comment]
@FantasticoFox :

* please no embedded remote content (youtube vids) in documentation

* go client, nim client ... what about java client?

* chunk, ref, manifest <- manifest much longer than the others perhaps split up, seems to lack heading after first figure

* please remove pss handshakes section

* there's a todo under go-client dev process

* team: I'm not with the ethereum foundation, and I guess I'm "track lead"

* there's plenty of warning output when building the docs

**Comment by FantasticoFox** [comment]
Can you please submit all those changes via pull request? Please leave the first video in. This will be removed after we restructured the website. Totally agree with you that it should not be there.

I'm not aware about a java client (?) yet. IOVLabs did not commit, they played with the thought but I think they want to see the reference implementation flying first.

**Comment by nolash** [comment]
> chunk, ref, manifest <- manifest much longer than the others perhaps split up, seems to lack heading after first figure

What do I do with this?

> there's a todo under go-client dev process

What do I do with this?

> there's plenty of warning output when building the docs

I really don't feel compelled to fix this, to be honest.

**Comment by FantasticoFox** [comment]
What do I do with this?

there's a todo under go-client dev process ==> Please move it where you think it belongs. Either DAPPDeveloper or Node-Operator. If you don't feel like you can address that alone we can have a session to speak it through.

there's plenty of warning output when building the docs ==> Ignore it for now.

chunk, ref, manifest <- manifest much longer than the others perhaps split up, seems to lack heading after first figure ==> Also leave it for now.

**Comment by thecryptofruit** [comment]
Hi, there's some old things in the docs (e.g. default network id 3) ... Is submitting a PR for e.g. https://github.com/ethersphere/swarm-docs/blob/master/contents/node_operator.rst now ok or is it better to wait till restructuring is complete?

**Comment by acud** [comment]
closing this as the working assumption is that this is `done`
