### ISSUE TITLE
Imprecise definition of SWIP

### ISSUE THREAD

**Issue by nolash** [ethersphere/swarm-docs#23]
From chapter 3

> The Swarm Specification Process is named SWIP (Swarm Improvement Proposal) 

SWIP may contain specs, but I thought its main use was as a protocol for defining _changes_ and _improvements_ to Swarm. This should be rewritten, and should contain rationale, recipe, description of process etc.

**Comment by attila-lendvai** [comment]
this entire repo is obsolete, please proceed to: https://github.com/ethersphere/bee-docs
